=== Deepikakadela/clocom/config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT configuration (numLines,database,project,algorithm,debug,removeEmpty,buildDatabase,gapSize)>

<!ELEMENT matching (minNumLines,matchAlgorithm,matchMode,gapSize)>
    <!ELEMENT minNumLines (#PCDATA)>
    <!ELEMENT matchAlgorithm (#PCDATA)>
    <!ELEMENT matchMode (#PCDATA)>
    <!ELEMENT gapSize (#PCDATA)>

<!ELEMENT projects (database,project,buildDatabase,buildTFIDF,loadTFIDF,loadDatabaseFilePaths)>
    <!ELEMENT database (#PCDATA)>
    <!ELEMENT project (#PCDATA)>
    <!ELEMENT buildDatabase (#PCDATA)>
    <!ELEMENT buildTFIDF (#PCDATA)>
    <!ELEMENT loadTFIDF (#PCDATA)>
    <!ELEMENT loadDatabaseFilePaths (#PCDATA)>

<!ELEMENT outputSettings (debug,removeEmpty,exportResults,resultPath)>
    <!ELEMENT debug (#PCDATA)>
    <!ELEMENT removeEmpty (#PCDATA)>
    <!ELEMENT exportResults (#PCDATA)>
    <!ELEMENT resultPath (#PCDATA)>

<!ELEMENT loadResults (#PCDATA)>

<!ELEMENT similarity (similarityRange,enableSimilarity)>
    <!ELEMENT similarityRange (#PCDATA)>
    <!ELEMENT enableSimilarity (#PCDATA)>

<!ELEMENT others (enableRepetitive,enableOneMethod)>
    <!ELEMENT enableRepetitive (#PCDATA)>
    <!ELEMENT enableOneMethod (#PCDATA)>

=== Deepikakadela/clocom/config.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE configuration SYSTEM "config.dtd">
<configuration>
    <matching>
        <minNumLines>3</minNumLines>
        <matchAlgorithm>0</matchAlgorithm>
        <gapSize>2</gapSize>
    </matching>
    <projects>
        <project>/Users/edmund/Documents/research/clocom/dbProjects/test1/</project>        
        <database>/Users/edmund/Documents/research/clocom/dbProjects/test2/</database>
        <loadDatabaseFilePaths>false</loadDatabaseFilePaths>
        <databaseFilePaths>/Users/edmund/Documents/research/clocom/fileList.obj</databaseFilePaths>
        <buildDatabase>true</buildDatabase>
        <buildTFIDF>false</buildTFIDF>
        <loadTFIDF>false</loadTFIDF>
    </projects>
    <outputSettings>
        <debug>false</debug>
        <removeEmpty>true</removeEmpty>
        <resultPath>/Users/edmund/Documents/research/comment-digger/results.txt</resultPath>
    </outputSettings>
    <loadResults>false</loadResults>
    <heuristics>
        <similarity>
            <similarityRange>extended</similarityRange>
            <enableSimilarity>true</enableSimilarity>
        </similarity>
    </heuristics>
</configuration>
